### ISSUE TITLE
net.sf.saxon.trans.Dynamic Error: Cannot convert string "0E-8"

### ISSUE THREAD

**Issue by ghost** [Intercent-ER/AGID-PEPPOL-DOCS#5]
La conversione della Fattura PA v1.2.2 in UBL Invoice/CreditNote 3.0 restituisce il seguente errore: net.sf.saxon.trans.Dynamic Error: Cannot convert string "0E-8".
[fatturaPa.xml.zip](https://github.com/Intercent-ER/AGID-PEPPOL-DOCS/files/11208428/fatturaPa.xml.zip)

**File aggiornati:**
[Fattura-PA-1.2.2-to-PEPPOL-BIS-05a-400_UBL-CreditNote-3.0_NoTIER.zip](https://github.com/Intercent-ER/AGID-PEPPOL-DOCS/files/11209943/Fattura-PA-1.2.2-to-PEPPOL-BIS-05a-400_UBL-CreditNote-3.0_NoTIER.zip)
[Fattura-PA-1.2.2-to-PEPPOL-BIS-05a-400_UBL-Invoice-3.0_NoTIER.zip](https://github.com/Intercent-ER/AGID-PEPPOL-DOCS/files/11209944/Fattura-PA-1.2.2-to-PEPPOL-BIS-05a-400_UBL-Invoice-3.0_NoTIER.zip)

**Comment by Intercent-ER** [comment]
Gent.mo/ma, 

Per poter convertire la fattura allegata nella versione UBL potrà utilizzare
il tool di conversione messo a disposizione sul sito:
[1]https://peppol-docs.agid.gov.it/docs/my_index_fatt.jsp e utilizzare il
batch di conversione "Converti FT FPA-PEPPOL BIS3.bat".
Abbiamo effettuato una prova e la fattura viene convertita. 

Per ulteriori chiarimenti rispondere a questa mail.

Distinti saluti,
Marco Mastrogiovanni

Staff Tecnico NoTIER

Intercent-ER
Agenzia Regionale per lo Sviluppo dei Mercati Telematici
Via Dei Mille,21 – 40121 Bologna
Numero Verde 800 810 799 (Opzione 2)

12/04/2023 09:40 - Matteo ha scritto:  

La conversione della Fattura PA v1.2.2 in UBL Invoice 3.0 restituisce il
seguente errore: net.sf.saxon.trans.Dynamic Error: Cannot convert string
"0E-8".
[2]fatturaPa.xml.zip

—
Reply to this email directly, [3]view it on GitHub, or [4]unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID:
***@***.***>



[1] https://peppol-docs.agid.gov.it/docs/my_index_fatt.jsp
[2] https://github.com/Intercent-ER/AGID-PEPPOL-DOCS/files/11208428/fatturaPa.xml.zip
[3] https://github.com/Intercent-ER/AGID-PEPPOL-DOCS/issues/5

**Comment by ghost** [comment]
Grazie
